[package]
name = "wgpu-font-renderer"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"
exclude = ["tests/fixtures"]
description = "GPU-Centered Font Rendering crate"
license = "MIT OR Apache-2.0"

[dependencies]
wgpu = { version = "30", default-features = true }
owned_ttf_parser = { version = "0.21.0", default-features = false, features = ["variable-fonts"] }
swash = "0.1.15"
bytemuck = { version = "1.16.0", features = ["derive"] }

[dev-dependencies]
winit = "0.30"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
pollster = "0.4"
serde_json = { version = "1.0.151", features = ["float_roundtrip"] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Window", "Document", "Element", "HtmlCanvasElement"] }
console_error_panic_hook = "0.1"

[[bench]]
name = "shader"
harness = false
